services:
  postgres:
    image: postgres:17
    container_name: wavebox-postgres
    environment:
      POSTGRES_DB: musicapp
      POSTGRES_USER: musicapp
      POSTGRES_PASSWORD: musicapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
