# Generated by Django 6.1.1 on 2026-09-10 16:18

import django.db.models.deletion
import music.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
                (
                    "normalized_name",
                    models.CharField(editable=False, max_length=180, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                ("normalized_title", models.CharField(editable=False, max_length=220)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "artwork",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=music.models.artwork_upload_path,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["artist__name", "title"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=140)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=220)),
                (
                    "audio_file",
                    models.FileField(upload_to=music.models.song_audio_upload_path),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "artwork",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=music.models.artwork_upload_path,
                    ),
                ),
                ("release_year", models.PositiveIntegerField(blank=True, null=True)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="songs",
                        to="music.artist",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="RecentlyPlayed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_seconds", models.PositiveIntegerField(default=0)),
                ("played_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recently_played",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_plays",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="music.playlist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_entries",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="PlaybackState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_seconds", models.PositiveIntegerField(default=0)),
                ("context_type", models.CharField(blank=True, max_length=40)),
                ("context_id", models.CharField(blank=True, max_length=80)),
                ("context_label", models.CharField(blank=True, max_length=180)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playback_states",
                        to="music.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LikedSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                fields=("artist", "normalized_title"), name="unique_album_per_artist"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlist",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_playlist_name"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["title"], name="music_song_title_8e56ff_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["created_at"], name="music_song_created_62d7ed_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recentlyplayed",
            constraint=models.UniqueConstraint(
                fields=("user", "song"), name="unique_recent_song"
            ),
        ),
        migrations.AddConstraint(
            model_name="playlistsong",
            constraint=models.UniqueConstraint(
                fields=("playlist", "order"), name="unique_playlist_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="likedsong",
            constraint=models.UniqueConstraint(
                fields=("user", "song"), name="unique_liked_song"
            ),
        ),
    ]
